hiddenPlayers:
worlds:
announcement:
  delay: 5
  message: Hello.
ops:
  - TranquilSea
  - MlgCheetoPuff
  - kalikakitty
  - legobmw99
  - Stealth5061
admins:
  - dinner1111
  - pepsidawg00
  - xannallax33
cannot-op:
spawns: