name: ServerUtils
main: io.github.Dinner1111.ServerUtils.ServerUtilsPlugin
version: 1.7.0.60
author: dinner1111
description: A powerful administrative plugin used for mass management.

commands:
  util-op:
    description: Utility for opping online players.
    usage: /util-op
    permission: Utils.Util.Op
    permission-message: Sorry, you don't have access to Utils.Util.Op.
  util-deop:
    description: Utility for deopping online players.
    usage: /util-deop
    permission: Utils.Util.Deop
    permission-message: Sorry, you don't have access to Utils.Util.Deop.
  util-unwhitelist:
    description: Utility for unwhitelisting online players.
    usage: /util-unwhitelist
    permission: Utils.Util.Unwhitelist
    permission-message: Sorry, you don't have access to Utils.Util.Unwhitelist.
  util-kick:
    description: Utility for kicking online players.
    usage: /util-kick [-uw]
    permission: Utils.Util.Kick
    permission-message: Sorry, you don't have access to Utils.Util.Kick.
  util-help:
    description: Utility explaining various util-related things.
    usage: /util-help [page]
    permission: Utils.Util.Help
    permission-message: Sorry, you don't have access to Utils.Util.Help.
  util-world:
    description: Utility for quickly making worlds.
    usage: /util-world [name]
    permission: Utils.Util.World
    permission-message: Sorry, you don't have access to Utils.Util.World.
  util-list:
    description: Utility listing all the usable utils.
    usage: /util-list [util]
    permission: Utils.Util.List
    permission-message: Sorry, you don't have access to Utils.Util.List.
  util-mute:
    description: Utility for muting online players.
    usage: /util-mute
    permission: Utils.Util.Mute
    permission-message: Sorry, you don't have access to Utils.Util.Mute.
  util-broadcast:
    description: Utility for broadcasting.
    usage: /util-broadcast
    permission: Utils.Util.Broadcast
    permission-message: Sorry, you don't have access to Utils.Util.Broadcast.
  util-kill:
    description: Utility for killing online players.
    usage: /util-kill
    permission: Utils.Util.Kill
    permission-message: Sorry, you don't have access to Utils.Util.Kill.
  util-version:
    description: Displays version info.
    usage: /util-version
    permission: Utils.Util.Version
    permission-message: Sorry, you don't have access to Utils.Util.Version.
  hide:
    description: Hides you or a specified player.
    usage: /hide [player]
    permission: Utils.Hide
    permission-message: Sorry, you don't have access to Utils.Hide.
  util-protect:
    description: Protects a world from all players but the owner.
    usage: /util-protect [player]
    permission: Utils.Util.Protect
    permission-message: Sorry, you don't have access to Utils.Util.Protect.
  util-config:
    description: Command for editing the config.
    usage: /util-config [player] [configuration section] [value]
    permission: Utils.Util.Config
    permission-message: Sorry, you don't have access to Utils.Util.Config.
  util-reload:
    description: Reloads all configs or display names.
    usage: /util-reload [-n[--aobg]]
    permission: Utils.Util.Reload
    permission-message: Sorry, you don't have access to Utils.Util.Reload.
  util-alert:
    description: Sends an alert out to all players.
    usage: /util-alerts [message]
    permission: Utils.Util.Alert
    permission-message: Sorry, you don't have access to Utils.Util.Alert.
  a:
    description: Admin chat.
    usage: /a [message]
    permission: Utils.Util.AdminChat
    permission-message: Sorry, you don't have access to Utils.AdminChat.
  silent:
    description: Silent commands.
    usage: /silent [op|deop|whitelist|unwhitelist|kick|ban] [player name]
    permission: Utils.Silent
    permission-message: Sorry, you don't have access to Utils.Silent.
  announcer:
    description: Announces a message every given minutes.
    usage: /announcer [minutes] [message]
    permission: Utils.Announcer
    permission-message: Sorry, you don't have access to Utils.Announcer.
  script:
    description: Runs a script.
    usage: /script [script]
  purge:
    description: Purges entities with a bang.
    usage: /purge
    permission: Utils.Purge
    permission-message: Sorry, you don't have access to Utils.Purge.
  whirl:
    description: Weeee... BOOM!
    usage: /whirl [player]
    permission: Utils.Whirl
    permission-message: Sorry, you don't have access to Utils.Whirl.
  run:
    description: Runs a command via Console.
    usage: /run [command]
    permission: Utils.Run
    permission-message: Sorry, you don't have access to Utils.Run.
  railgun:
    description: Extreme destruction.
    usage: /railgun
    permission: Utils.Railgun
    permission-message: Sorry, you don't have access to Utils.Railgun.
  vel:
    description: Sets, adds or multiplies your current velocity.
    usage: /vel [set|add|multiply] [x] [y] [z]
    permission: Utils.Velocity
    permission-message: Sorry, you don't have access to Utils.Velocity.
  rq:
    description: Rage quittin' for days.
    usage: /rq [-c]
    permission: Utils.RageQuit
    permission-message: Sorry, you don't have access to Utils.RageQuit.